version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: workwise_postgres
    restart: always
    environment:
      POSTGRES_USER: workwise
      POSTGRES_PASSWORD: workwise123
      POSTGRES_DB: workwise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: workwise_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workwise.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
